plugins:
  subscription_server_enabled:
    client: true
    default: true
  subscription_server_supplier_name: ''
  subscription_server_subscriptions:
    type: list
    default: ''
  subscription_server_iam_access_key: ''
  subscription_server_iam_secret_access_key: ''
  subscription_server_iam_region: 'us-east-1'